### ISSUE TITLE
Permissions error on replicationset deployment

### ISSUE THREAD

**Issue by thomasklinger1234** [aws-cloudformation/aws-cloudformation-resource-providers-ssm-incidents#10]
Hey,

when I deploy a Replicationset resource with the following configuration:

```
Resources:
  SSMIncidentsReplicationSet:
    Type: AWS::SSMIncidents::ReplicationSet
    Properties:
      DeletionProtected: !If [ IsProd, true, false ]
      Regions:
        - RegionName: !Sub ${AWS::Region}
```

I get the following error:

> Resource handler returned message: "User: arn:aws:sts::591575155923:assumed-role/UluruResourceHandlerLambdaExecutionRole-591575155923fra/AWS-SSMIncidents-ReplicationSe637361254986-Handler-1uvd9sdg06df4 is not authorized to perform: ssm-incidents:UpdateDeletionProtection on resource: arn:aws:ssm-incidents::<ACCOUNT>:replication-set/86be72f9-f3c6-4ea2-120d-4a7615fb17e6 (Service: SsmIncidents, Status Code: 403, Request ID: 3770c4c0-81a6-4ef3-a815-b18228fea7e3, Extended Request ID: null)" (RequestToken: 5d646d2e-ed8c-f2bf-7b66-f9f0f64af585, HandlerErrorCode: GeneralServiceException)

Environment:
- Region: eu-central-1
- Role: with full administrator permissions, no SCPs in place
- Deployment from my local machine
